all:
  hosts:
    standby-cluster-node1:
      ansible_host: 10.200.200.4
      ip: 10.200.200.4
      access_ip: 10.200.200.4
    standby-cluster-node2:
      ansible_host: 10.200.200.5
      ip: 10.200.200.5
      access_ip: 10.200.200.5
    standby-cluster-node3:
      ansible_host: 10.200.200.6
      ip: 10.200.200.6
      access_ip: 10.200.200.6
  children:
    kube_control_plane:
      hosts:
        standby-cluster-node1:
        standby-cluster-node2:
        standby-cluster-node3:
    kube_node:
      hosts:
        standby-cluster-node1:
        standby-cluster-node2:
        standby-cluster-node3:
    etcd:
      hosts:
        standby-cluster-node1:
        standby-cluster-node2:
        standby-cluster-node3:
    k8s_cluster:
      children:
        kube_control_plane: