apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: bmo-elastic-cluster
  namespace: elastic-system 
spec:
  version: 9.1.3            
  nodeSets:
    - name: default      
      count: 1               
      config:
        node.store.allow_mmap: false
        node.roles: ["master", "data", "ingest"]  
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1
