apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: bmo-kibana
  namespace: elastic-system
spec:
  version: 9.1.3
  count: 1
  elasticsearchRef:
    name: bmo-elastic-cluster
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
