apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/syn-opt: Prune=false
    kustomize.toolkit.fluxcd.io/prune: "false"
  name: bmo-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bmo-app-role
  namespace: bmo-app
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bmo-app-sa
  namespace: bmo-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bmo-app-rolebinding
  namespace: bmo-app
subjects:
  - kind: ServiceAccount
    name: bmo-app-sa
    namespace: bmo-app
roleRef:
  kind: Role
  name: bmo-app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bmo-git
  namespace: argocd
spec:
  interval: 1m0s
  ref:
    branch: main
  url: git@github.com:test/bmo.git
  secretRef:
    name: github-repo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bmo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:test/bmo.git
    targetRevision: HEAD
    path: test-api
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bmo-kustomize
  namespace: bmo-app
  annotations:
    description: "Kustomization for BMO using SOPS decryption"
spec:
  interval: 1m0s
  path: ./clusters/hot-cluster/test-api
  targetNamespace: argocd
  sourceRef:
    kind: GitRepository
    name: bmo-git
    namespace: argocd
  decryption:
    provider: sops
    secretRef:
      name: sops