apiVersion: cert-manager.io/v1
kind: Clusterissuer
metadata:
  name: prod-issuer
  namespace: cert-manager
spec:
  acme:
    email: bmo-test@bmo.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx 